### ISSUE TITLE
not possible to compile on ubuntu 16.04

### ISSUE THREAD

**Issue by Dazgard** [linjam/linjam#78]
Hello,

thank for the app good to see a linux effort on ninjman !!

I can compile it on ubuntu 16.04. I have the below error:

```
In file included from ../../Source/LinJamConfig.h:15:0,
                 from ../../Source/LinJam.h:30,
                 from ../../Source/Channels.cpp:22:
../../Source/Constants.h:510:52: error: ‘SAVE_AUDIO_DELETE_ASAP’ is not a member of ‘NJClient’
   static const int  DEFAULT_SAVE_AUDIO_MODE = (int)NJClient::SAVE_AUDIO_DELETE_ASAP ;
                                                    ^
../../Source/Constants.h:511:52: error: ‘SAVE_MIXDOWN_NONE’ is not a member of ‘NJClient’
   static const int  DEFAULT_MIXDOWN_MODE    = (int)NJClient::SAVE_MIXDOWN_NONE ;
                                                    ^
../../Source/Constants.h:513:52: error: ‘DEBUG_LEVEL_SILENT’ is not a member of ‘NJClient’
   static const int  DEFAULT_DEBUG_LEVEL     = (int)NJClient::DEBUG_LEVEL_SILENT ;
                                                    ^
../../Source/Constants.h:516:50: error: ‘SUBSCRIBE_DENY’ is not a member of ‘NJClient’
   static const int DEFAULT_SUBSCRIBE_MODE = (int)NJClient::SUBSCRIBE_DENY ;
                                                  ^
../../Source/Constants.h:519:54: error: ‘DEFAULT_N_INPUTS’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_N_INPUTS        = (int)audioStreamer::DEFAULT_N_INPUTS ;
                                                      ^
../../Source/Constants.h:520:54: error: ‘DEFAULT_N_OUTPUTS’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_N_OUTPUTS       = (int)audioStreamer::DEFAULT_N_OUTPUTS ;
                                                      ^
../../Source/Constants.h:521:54: error: ‘DEFAULT_SAMPLERATE’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_SAMPLERATE      = (int)audioStreamer::DEFAULT_SAMPLERATE ;
                                                      ^
../../Source/Constants.h:522:54: error: ‘DEFAULT_BITDEPTH’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_BITDEPTH        = (int)audioStreamer::DEFAULT_BITDEPTH ;
                                                      ^
In file included from ../../Source/LinJamConfig.h:15:0,
                 from ../../Source/LinJam.h:30,
                 from ../../Source/Channel.cpp:22:
../../Source/Constants.h:510:52: error: ‘SAVE_AUDIO_DELETE_ASAP’ is not a member of ‘NJClient’
   static const int  DEFAULT_SAVE_AUDIO_MODE = (int)NJClient::SAVE_AUDIO_DELETE_ASAP ;
                                                    ^
../../Source/Constants.h:523:54: error: ‘WIN_AUDIO_WAVE’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_WIN_AUDIO_IF    = (int)audioStreamer::WIN_AUDIO_WAVE ;
                                                      ^
../../Source/Constants.h:511:52: error: ‘SAVE_MIXDOWN_NONE’ is not a member of ‘NJClient’
   static const int  DEFAULT_MIXDOWN_MODE    = (int)NJClient::SAVE_MIXDOWN_NONE ;
                                                    ^
../../Source/Constants.h:513:52: error: ‘DEBUG_LEVEL_SILENT’ is not a member of ‘NJClient’
   static const int  DEFAULT_DEBUG_LEVEL     = (int)NJClient::DEBUG_LEVEL_SILENT ;
                                                    ^
../../Source/Constants.h:556:54: error: ‘NIX_AUDIO_JACK’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_NIX_AUDIO_IF    = (int)audioStreamer::NIX_AUDIO_JACK ;
                                                      ^
../../Source/Constants.h:516:50: error: ‘SUBSCRIBE_DENY’ is not a member of ‘NJClient’
   static const int DEFAULT_SUBSCRIBE_MODE = (int)NJClient::SUBSCRIBE_DENY ;
                                                  ^
../../Source/Constants.h:519:54: error: ‘DEFAULT_N_INPUTS’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_N_INPUTS        = (int)audioStreamer::DEFAULT_N_INPUTS ;
                                                      ^
../../Source/Constants.h:520:54: error: ‘DEFAULT_N_OUTPUTS’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_N_OUTPUTS       = (int)audioStreamer::DEFAULT_N_OUTPUTS ;
                                                      ^
../../Source/Constants.h:521:54: error: ‘DEFAULT_SAMPLERATE’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_SAMPLERATE      = (int)audioStreamer::DEFAULT_SAMPLERATE ;
                                                      ^
../../Source/Constants.h:522:54: error: ‘DEFAULT_BITDEPTH’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_BITDEPTH        = (int)audioStreamer::DEFAULT_BITDEPTH ;
                                                      ^
../../Source/Constants.h:523:54: error: ‘WIN_AUDIO_WAVE’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_WIN_AUDIO_IF    = (int)audioStreamer::WIN_AUDIO_WAVE ;
                                                      ^
../../Source/Constants.h:556:54: error: ‘NIX_AUDIO_JACK’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_NIX_AUDIO_IF    = (int)audioStreamer::NIX_AUDIO_JACK ;
                                                      ^
In file included from ../../Source/LinJamConfig.h:15:0,
                 from ../../Source/LinJam.h:30,
                 from ../../Source/Chat.cpp:22:
../../Source/Constants.h:510:52: error: ‘SAVE_AUDIO_DELETE_ASAP’ is not a member of ‘NJClient’
   static const int  DEFAULT_SAVE_AUDIO_MODE = (int)NJClient::SAVE_AUDIO_DELETE_ASAP ;
                                                    ^
../../Source/Constants.h:511:52: error: ‘SAVE_MIXDOWN_NONE’ is not a member of ‘NJClient’
   static const int  DEFAULT_MIXDOWN_MODE    = (int)NJClient::SAVE_MIXDOWN_NONE ;
                                                    ^
../../Source/Constants.h:513:52: error: ‘DEBUG_LEVEL_SILENT’ is not a member of ‘NJClient’
   static const int  DEFAULT_DEBUG_LEVEL     = (int)NJClient::DEBUG_LEVEL_SILENT ;
                                                    ^
../../Source/Constants.h:516:50: error: ‘SUBSCRIBE_DENY’ is not a member of ‘NJClient’
   static const int DEFAULT_SUBSCRIBE_MODE = (int)NJClient::SUBSCRIBE_DENY ;
                                                  ^
../../Source/Constants.h:519:54: error: ‘DEFAULT_N_INPUTS’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_N_INPUTS        = (int)audioStreamer::DEFAULT_N_INPUTS ;
                                                      ^
../../Source/Constants.h:520:54: error: ‘DEFAULT_N_OUTPUTS’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_N_OUTPUTS       = (int)audioStreamer::DEFAULT_N_OUTPUTS ;
                                                      ^
../../Source/Constants.h:521:54: error: ‘DEFAULT_SAMPLERATE’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_SAMPLERATE      = (int)audioStreamer::DEFAULT_SAMPLERATE ;
                                                      ^
../../Source/Constants.h:522:54: error: ‘DEFAULT_BITDEPTH’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_BITDEPTH        = (int)audioStreamer::DEFAULT_BITDEPTH ;
                                                      ^
../../Source/Constants.h:523:54: error: ‘WIN_AUDIO_WAVE’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_WIN_AUDIO_IF    = (int)audioStreamer::WIN_AUDIO_WAVE ;
                                                      ^
../../Source/Constants.h:556:54: error: ‘NIX_AUDIO_JACK’ is not a member of ‘audioStreamer’
   static const int    DEFAULT_NIX_AUDIO_IF    = (int)audioStreamer::NIX_AUDIO_JACK ;
                                                      ^
```

K.

**Comment by bill-auger** [comment]
yes sry - this is not so well documented yet so i will explain to be clear to all - linjam itself is a front-end for the client part of libninjam and so is dependent on the specific version of libninjam - libninjam is the entire ninjam system (server, clients, and various support tools) - the current master branch of libninjam is still at the pristine state as forked from tobias's original work which supports with the command line client and the gNinjam GTK2 client on linux - those missing constants you are hitting are among my additions for the next version which will slightly break compatibility with gNinjam (unless i update that also) but allow both libninjam (and linjam) to be cross-platform and ideally the standard base for future servers and clients - i have been hesitant to push the new version into master just yet because one does not wish to break the API regularly but the original ninjam code has not been updated in over ten years and is the epitome of "legacy code" "rotting on the vine" as the say so some things really should change 

linjam is the first step in that direction and requires the changes present in the current development branches of libninjam such as [the 'linux' branch](https://github.com/libninjam/libninjam/tree/linux) - the most recent work i have done was in creating [debian packages](https://packagecloud.io/ninjam/ninjam/) to manage dependencies but i dont know if they will install on the latest ubuntu - if not then compile the 'linux' branch of libninjam and compile linjam against that

i have been attending more to other projects lately but slowly i have been working to make this into a community effort to propose, vote, and add useful features to ninjam (such as a shared chord chart) - many such features will require the server and clients to be based on the updated libninjam so it will take a fair deal of co-operation from the user community and server admins going forward

that being said - linjam is quite usable as a standard ninjam client in the current state - there are many new features i plan to add to it and i really do hope to get back working on it soon - plz do report any bugs you might find and spread the word (especially if you know some developers that would like to contribute to the future of ninjam) - as i see more interest then i will be compelled to focus on it more myself also
